services:
  front:
    image: ${IMAGEN_FRONT}
    restart: always
    ports:
      - "${PORT_FRONT}:443"
      - "${PORT_FRONT_ALTERNATIVO}:80"
    env_file:
      - .env
    networks:
      - crm
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://backend:8000/api
      - NODE_ENV=production

  backend:
    image: ${IMAGEN_BACKEND}
    restart: always
    ports:
      - "${PORT_BACKEND}:8000"
    env_file:
      - .env
    networks:
      - crm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s        # Reduced from 30s
      timeout: 5s          # Reduced from 10s
      retries: 5          # Increased from 3
      start_period: 15s   # Reduced from 30s

networks:
  crm:
    driver: bridge
    name: crm_network    # Added explicit network name