services:
  front:
    image: ${IMAGEN_FRONT}
    restart: always
    ports:
      - "${PORT_FRONT}:443"
      - "${PORT_FRONT_ALTERNATIVO}:80"
    env_file:
      - .env
    networks:
      - crm
    depends_on:
      - backend
  backend:
    image: ${IMAGEN_BACKEND}
    restart: always
    ports:
      - "${PORT_BACKEND}:8000"  # Updated to match the API port
    env_file:
      - .env
    networks:
      - crm

networks:
  crm:
    driver: bridge